# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      MONGO_INITDB_DATABASE: dvmdash
    command: ["mongod", "--auth", "--bind_ip_all"]
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" mongodb://admin:adminpass@localhost:27017/admin
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./infrastructure/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongodb_data:/data/db

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: dvmdash
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devuser -d dvmdash" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build:
      context: .
      dockerfile: ./backend/celery_worker/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app/backend
      - celery_logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: [ "CMD-SHELL", "celery -A celery_worker.src.tasks inspect ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  event_collector:
    build:
      context: .
      dockerfile: ./backend/event_collector/Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LOG_LEVEL=DEBUG  # Can be DEBUG, INFO, WARNING, ERROR, CRITICAL
      - RELAYS=wss://relay.damus.io,wss://relay.primal.net,wss://relay.dvmdash.live,wss://relay.f7z.xyz,wss://relayable.org
      - DAYS_LOOKBACK=7
    healthcheck:
      test: [ "CMD", "python", "-c", "import redis; redis.from_url(os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')).ping()" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ./backend:/app/backend
      - event_collector_logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  batch_processor:
    build:
      context: .
      dockerfile: ./backend/batch_processor/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend:/app/backend
      - batch_processor_logs:/app/logs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: [ "CMD", "python", "-c", "import redis; redis.from_url(os.getenv('REDIS_URL', 'redis://redis:6379/0')).ping()" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


volumes:
  mongodb_data:
  postgres_data:
  redis_data:
  celery_logs:
  event_collector_logs:
  batch_processor_logs: