apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres_pipeline:5432
    user: devuser
    secureJsonData:
      password: devpass
    jsonData:
      database: dvmdash_pipeline
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true