= Nostr DVM Kind 5xxx
:toc:
:toclevels: 3
:source-highlighter: highlight.js

== Introduction

Kind 5394 events represent Data Vending Machine (DVM) requests on the Nostr network. The input for a kind 5394 event includes fields such as "id", "sig", "kind", "tags", "pubkey", "content", and "created_at". The output of analyzing kind 5394 events provides insights into the prevalence of different fields in DVM requests and includes a complete example event for reference.

=== Analysis

An analysis of Nostr Data Vending Machine (DVM) events of kind 5394.
Kind 5394 represents DVM requests.

The analysis is based on data collected from the DVM network by [DVMDash](https://dvmdash.live), an online monitoring and debugging platform, and shows the prevalence of different fields in these events.

== Kind 5394: DVM Request Events (Kind 5394)

=== Summary

Total events analyzed: 22

=== Field Prevalence

[options="header"]
|===
|Field|Percentage|Example
|id|100.00%|`d9fb3af17f7eb65b8b0b42bc2f821e7c96902cf40240109...`
|_id|100.00%|`{"$oid": "6744c34665cdac2eea1ea60f"}`
|sig|100.00%|`60c5496e37abe8ecceca04b589745986ccbdcde8ae46635...`
|kind|100.00%|`5394`
|tags|100.00%|`[]`
|pubkey|100.00%|`dee7cd029619f4cc0a9a64bf6aca8cda6f784872d709245...`
|content|100.00%|`const msgs = [
    "Hello, Nostr",
    "Hola, N...`
|created_at|100.00%|`1732559686`
|===

=== Complete Example Event

Event with ID: `d9fb3af17f7eb65b8b0b42bc2f821e7c96902cf4024010936812ae98e1714d8d`

[source,json]
----
{
  "id": "d9fb3af17f7eb65b8b0b42bc2f821e7c96902cf4024010936812ae98e1714d8d",
  "_id": {
    "$oid": "6744c34665cdac2eea1ea60f"
  },
  "sig": "60c5496e37abe8ecceca04b589745986ccbdcde8ae46635d89fe367a0e6d344dd7234c8bb0cc7699a05965ee3f81da19ab57ce39fabf18e6acccdd62fcb21bd6",
  "kind": 5394,
  "tags": [],
  "pubkey": "dee7cd029619f4cc0a9a64bf6aca8cda6f784872d70924509b93092023bbbec2",
  "content": "const msgs = [\n    \"Hello, Nostr\",\n    \"Hola, Nostr\",\n    \"Ciao, Nostr\", \n    \"\u3053\u3093\u306b\u3061\u306f, Nostr\"\n]\n\nvar index = 0\n\nfunction changeMessage() {\n    // Refresh DIV with new content.\n    index = (index+1) % msgs.length\n    document.getElementById(\"msg\").innerHTML = msgs[index]\n}\n\nlet reload = window.setInterval('changeMessage()', 1000);",
  "created_at": 1732559686
}
----

