= Nostr DVM Kind 5xxx
:toc:
:toclevels: 3
:source-highlighter: highlight.js

== Introduction

Kind 5389 events represent Data Vending Machine (DVM) requests on the Nostr network. The input for a kind 5389 event includes a unique event ID, a cryptographic signature, the public key of the requester, and an encrypted content field. The output of processing a kind 5389 event is the fulfillment of the DVM request, which may involve providing requested data or performing a requested action, depending on the specifics of the request encoded in the content field.

=== Analysis

An analysis of Nostr Data Vending Machine (DVM) events of kind 5389.
Kind 5389 represents DVM requests.

The analysis is based on data collected from the DVM network by [DVMDash](https://dvmdash.live), an online monitoring and debugging platform, and shows the prevalence of different fields in these events.

== Kind 5389: DVM Request Events (Kind 5389)

=== Summary

Total events analyzed: 1

=== Field Prevalence

[options="header"]
|===
|Field|Percentage|Example
|id|100.00%|`d7052da15a36d029a20939ba5bcea21e6e2aba54c9412fe...`
|_id|100.00%|`{"$oid": "66de608bc8859972df94efb8"}`
|sig|100.00%|`fd4351bda3d006369241b06c359d523ff5701b1d4d742c3...`
|kind|100.00%|`5389`
|tags|100.00%|`[]`
|pubkey|100.00%|`c9bff857765febaaf8b936c2a59c72afced944f30235e87...`
|content|100.00%|`ApsINEkfiyiPDaaMXvz+WCKlNka8339ydLB+u6wnFKg8FaJ...`
|created_at|100.00%|`1725849739`
|===

=== Complete Example Event

Event with ID: `d7052da15a36d029a20939ba5bcea21e6e2aba54c9412fe5d675d03f93ecd675`

[source,json]
----
{
  "id": "d7052da15a36d029a20939ba5bcea21e6e2aba54c9412fe5d675d03f93ecd675",
  "_id": {
    "$oid": "66de608bc8859972df94efb8"
  },
  "sig": "fd4351bda3d006369241b06c359d523ff5701b1d4d742c36c65fa0f15c68ac2194aa6ededac49a83a1230085146d377108609eb756f75c07309f4eb23941ff9b",
  "kind": 5389,
  "tags": [],
  "pubkey": "c9bff857765febaaf8b936c2a59c72afced944f30235e87c3e9a8841ccfca679",
  "content": "ApsINEkfiyiPDaaMXvz+WCKlNka8339ydLB+u6wnFKg8FaJLWZ9RW0dd+CQYbZLwhuV9PsIO3H5QJBHaT/ACtWMb8N0clBmVsOnXDa+iXgziNsbHywcczMrZknEs86rAqJl3",
  "created_at": 1725849739
}
----

